DAO-384 Added RIF-Token contract
RootstockCollective/dao-contracts pull request #1
Opened 2024-06-12 15:26 UTC by Freshenext

Notes:
Had to add RIFTokenTest.sol to solhint ignore list because it was complaining: 
**Compiler version ^0.4.24 does not satisfy the ^0.8.0 semver requirement**

2024-06-13 03:19 UTC, rodrigoncalves approved these changes
Looks perfect. Just add some newline at end of some files and we're good to go.

2024-06-13 03:19 UTC, rodrigoncalves commented on .gitignore
> +.idea
Add a newline at end of file here.

2024-06-13 03:19 UTC, rodrigoncalves commented on .solhintignore
> +contracts/RIFTokenTest.sol
And here.

2024-06-13 03:19 UTC, rodrigoncalves commented on contracts/RIFTokenTest.sol
> +}
And here.

2024-06-13 03:28 UTC, rodrigoncalves requested changes
Actually it's better to rename this file to `RIFToken.test.ts`.

2024-06-13 04:50 UTC, Freshenext commented
> Actually it's better to rename this file to `RIFToken.test.ts`.

Yep! Done

2024-06-13 04:51 UTC, rodrigoncalves approved these changes
LG

2024-06-14 12:17 UTC, sleyter93 approved these changes
Great job.

2024-06-14 13:30 UTC, jessgusclark approved these changes

2024-06-14 13:30 UTC, merged