`VotingVanguardsRootstockCollective` NFT smart contract
RootstockCollective/dao-contracts pull request #102
Opened 2024-12-06 04:43 UTC by shenshin

# What

##  `VotingVanguardsRootstockCollective` NFT smart contract

TLDR:
- The contract fully (maybe almost) complies to  [the requirements from the ticked](https://rsklabs.atlassian.net/browse/DAO-861)
- A bunch of tests for different scenarios
- Deployment script
- Comprehensive test including gas fee measuring 

This pull request introduces a new smart contract for the Voting Vanguards Rootstock Collective, along with corresponding configuration, deployment, and testing updates. The most important changes include the creation of the `VotingVanguardsRootstockCollective` contract, the addition of a deployment module, parameter configuration for testnet, and comprehensive tests for the new contract.

2024-12-09 08:39 UTC, TravellerOnTheRun requested changes

2024-12-09 08:39 UTC, TravellerOnTheRun commented on contracts/NFT/VotingVanguardsRootstockCollective.sol
> +    uint256 lastCheckIndex = firstCheckIndex > proposalCount ? firstCheckIndex - proposalCount : 0;
The variable name chosen for stored number of proposals to check confuses me, let's rename to `proposalsAmountToCheck`, `proposalsAmount`

2024-12-09 08:39 UTC, TravellerOnTheRun commented on contracts/NFT/VotingVanguardsRootstockCollective.sol
> +    uint256 firstCheckIndex = governor.proposalCount();
This is not the index, should it be  `- 1`?

2024-12-09 08:39 UTC, TravellerOnTheRun commented on contracts/NFT/VotingVanguardsRootstockCollective.sol
> +      (uint256 proposalId, , , , ) = governor.proposalDetailsAt(i - 1);
let's move that to avoid confusion to `firstCheckIndex`

2024-12-09 08:39 UTC, TravellerOnTheRun commented on test/Vanguard.test.ts
> +  const enfranchise = async (rif: RIFToken, stRIF: StRIFToken) => {
fancy word :D

2024-12-09 08:39 UTC, TravellerOnTheRun commented on test/Vanguard.test.ts
> +  const createProposal = async (governor: GovernorRootstockCollective) => {
why did you not test on `TESTNET`? Hardhat network is not guaranteed to have the same amount of gas

2024-12-09 08:39 UTC, TravellerOnTheRun commented on test/Vanguard.test.ts
> +        expect(await governor.name()).to.equal('GovernorRootstockCollective')
Why do you redeploy the governor?

2024-12-09 08:39 UTC, TravellerOnTheRun commented on test/Vanguard.test.ts
> +      it('Number of proposal to search should be set', async () => {
You have two of the same tests, look up `it('number of past votes to be checked should be set up'`

2024-12-10 09:56 UTC, TravellerOnTheRun requested changes
Still one change left to avoid confusion and have a better code readability in the future

2024-12-10 09:56 UTC, TravellerOnTheRun commented on contracts/NFT/VotingVanguardsRootstockCollective.sol
> +    uint256 firstCheckIndex = governor.proposalCount();
Still think it's not an index and hence you need to make one

2024-12-10 19:19 UTC, rodrigoncalves approved these changes

2024-12-11 11:10 UTC, TravellerOnTheRun approved these changes

2024-12-11 11:10 UTC, merged