feat: added a guardian to cancel malicious proposals
RootstockCollective/dao-contracts pull request #28
Opened 2024-07-30 12:46 UTC by bezerrablockchain

As an idea got from GovernorAlpha (Compound) a governor address is added, the purpose of it is just to keep the DAO away from some suspicious and/or not acceptable proposals

2024-07-30 12:50 UTC, TravellerOnTheRun commented on contracts/Governor.sol
> +    if (_msgSender() != guardian && _msgSender() != proposalProposer(proposalId)) {
Wait a sec, it seems from the code that `proposalProposer` will not be able to cancel the proposal unless it's also the guardian, isn't it supposed to be `||` instead of `&&`?

2024-07-30 12:54 UTC, bezerrablockchain commented on contracts/Governor.sol
> +    if (_msgSender() != guardian && _msgSender() != proposalProposer(proposalId)) {
this if is not to execute the cancel, but for revert case the sender is not the guardian or the proposer

2024-07-30 12:55 UTC, bezerrablockchain commented on contracts/Governor.sol
> +    if (_msgSender() != guardian && _msgSender() != proposalProposer(proposalId)) {
anyway I´ll write a test for this just to be sure

2024-08-27 16:30 UTC, cybervoid0 requested changes
Please add detailed comments to the functions

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +  // keccak256(abi.encode(uint256(keccak256("openzeppelin.storage.Governor")) - 1)) & ~bytes32(uint256(0xff))
do you want to keep these comments here or maybe remove them?
Or is this explanation? I didn't get it

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +  // keccak256(abi.encode(uint256(keccak256("openzeppelin.storage.GovernorStorage")) - 1)) & ~bytes32(uint256(0xff))
is it a comment?

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +    bytes32((2 ** (uint8(type(ProposalState).max) + 1)) - 1);
maybe could you explain in comments what this means. Honestly, I don't understand what that means

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +    0x7c712897014dbe49c045ef1299aa2d5f9e67e48eea4403efa21f1e0f3ac0cb00;
also needs comments on where this value comes from and why

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +    0x7fd223d3380145bd26132714391e777c488a0df7ac2dd4b66419d8549fb3a600;
also needs comments on where this value comes from and why

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +  function validateStateBitmap(
would be nice to have some kind of comment here

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +  function getGovernorStorage() private pure returns (GovernorStorage storage $) {
would be nice to have some kind of comment here

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +  function getGovernorStorageStorage() private pure returns (GovernorStorageStorage storage $) {
would be nice to have some kind of comment here

2024-08-27 16:30 UTC, cybervoid0 commented on contracts/Governor.sol
> +  function cancel(
would be nice to have some kind of comment here (Especially to Public function!)

2024-08-27 17:30 UTC, bezerrablockchain commented on contracts/Governor.sol
> +  // keccak256(abi.encode(uint256(keccak256("openzeppelin.storage.Governor")) - 1)) & ~bytes32(uint256(0xff))
this comment is default, this is just to explain how the contract gets the slot address

2024-08-27 17:30 UTC, bezerrablockchain commented on contracts/Governor.sol
> +  // keccak256(abi.encode(uint256(keccak256("openzeppelin.storage.GovernorStorage")) - 1)) & ~bytes32(uint256(0xff))
same as above

2024-08-27 17:33 UTC, bezerrablockchain commented on contracts/Governor.sol
> +    bytes32((2 ** (uint8(type(ProposalState).max) + 1)) - 1);
This sets a bunch of 1 for the ALL_PROPOSAL_STATES, eg.  Lets say we have 4 states, so it would be 1111 = 2^3
4 states -1 = 3

2024-08-27 17:34 UTC, bezerrablockchain commented on contracts/Governor.sol
> +    0x7c712897014dbe49c045ef1299aa2d5f9e67e48eea4403efa21f1e0f3ac0cb00;
GovernorStorageLocation =
    0x7c712897014dbe49c045ef1299aa2d5f9e67e48eea4403efa21f1e0f3ac0cb00;
this Rvalue is the keccak256 hash from the string documented above this line

2024-08-27 17:35 UTC, bezerrablockchain commented on contracts/Governor.sol
> +    0x7fd223d3380145bd26132714391e777c488a0df7ac2dd4b66419d8549fb3a600;
its not necessary this is pretty acceptable for upgradable contracts

2024-08-29 16:14 UTC, cybervoid0 approved these changes

2024-08-29 16:14 UTC, merged