feat: added upgrade script for StRIFToken
RootstockCollective/dao-contracts pull request #54
Opened 2024-09-05 00:24 UTC by bezerrablockchain

### What?
Verify if the StRIFToken.sol contract really supports an upgrade.

### Why?
To be sure that our StRIFToken.sol contract supports an upgrade in production we should test it in testnet first

### How?
Was created a script and a config file working in conjunction to execute the upgrade

2024-09-05 09:03 UTC, TravellerOnTheRun requested changes
Minor tweaks to comments

2024-09-05 09:03 UTC, TravellerOnTheRun commented on ignition/modules/StRIFTokenUpgradeModule.ts
> +  // Load the governor proxy address
stRIF proxy address maybe?

2024-09-05 09:03 UTC, TravellerOnTheRun commented on ignition/modules/StRIFTokenUpgradeModule.ts
> +  //`GovernorV2` is the new version
stRIFV2?

2024-09-05 09:03 UTC, TravellerOnTheRun commented on ignition/modules/StRIFTokenUpgradeModule.ts
> +    id: 'upgrade_governor',
upgrade_stRIF?

2024-09-06 18:55 UTC, cybervoid0 reviewed
Tests are missing here.

2024-09-06 18:55 UTC, cybervoid0 commented on contracts/test/StRIFTokenV2.sol
> +  function reInitialize(uint64 versionAfterUpgrade) public reinitializer(versionAfterUpgrade) onlyProxy {
I suggest renaming it to `initializeV2` because later there will be v3 and what will happen with `reInitialize` since you cant override it?

2024-09-09 22:33 UTC, bezerrablockchain commented on contracts/test/StRIFTokenV2.sol
> +  function reInitialize(uint64 versionAfterUpgrade) public reinitializer(versionAfterUpgrade) onlyProxy {
Just kept as the standard following the same for governor upgrade

2024-09-09 22:37 UTC, cybervoid0 approved these changes

2024-09-10 08:07 UTC, TravellerOnTheRun approved these changes
Looks great! Let's merge that in

2024-09-10 08:07 UTC, merged